site_name: Home Assistant Supernotifier
site_url: https://jeyrb.github.io/hass_supernotify/
site_description: Advanced, concise, flexible notification upgrade for Home Assistant

repo_name: jeyrb/hass_supernotify
repo_url: https://github.com/jeyrb/hass_supernotify

theme:
  name: material
  highlightjs: true
plugins:
  - search
  - codeinclude:
      title_mode: none
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - smarty
  - toc:
      permalink: true
  - sane_lists
  - pymdownx.snippets:
      check_paths: true


