reload:
enquire_deliveries_by_scenario:
enquire_last_notification:
enquire_active_scenarios:
purge_archive:
  fields:
    days:
      required: false
      example: 5
      selector:
        number:
          min: 0
          unit_of_measurement: days
